backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "image-gallery"
    label: "Image"
    folder: "src/galleries/images"
    create: true
    slug: "{{slug}}-{{day}}-{{month}}-{{year}}"
    fields:
      - {
        label: "Template Key",
        name: "templateKey",
        widget: "hidden",
        default: "image-gallery"
      }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
        label: "Image",
        name: image, 
        widget: object,
        fields:
          [
            { label: Image, name: src, widget: image },
            {
              label: "Image description",
              name: alt,
              widget: string
            }
          ]
      }
  - name: "Members"
    label: "Member"
    folder: "src/galleries/members"
    create: true
    slug: "{{slug}}-{{day}}-{{month}}-{{year}}"
    fields:
      - {
        label: "Template Key",
        name: "templateKey",
        widget: "hidden",
        default: "members"
      }
      - { label: "Full name", name: "fullName", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { 
          label: "Position",
          name: "position",
          widget: "select",
          options:
            [
              { label: "Predsjednik Udruge", value: "president" },
              { label: "Tajnik Udruge", value: "secretary" },
              { label: "Članovi Upravnog Odbora", value: "member" }
            ]
        }
      - {
        label: "Image",
        name: image, 
        widget: object,
        fields:
          [
            { label: Image, name: src, widget: image },
            {
              label: "Image description",
              name: alt,
              widget: string
            }
          ]
      }
  - name: "config"
    label: "Configuration"
    files:
      - file: "src/config/header/index.md"
        label: "Header"
        name: "header"
        fields:
          - {
              label: "Config Type",
              name: "configType",
              widget: "hidden",
              default: "header",
            }
          - { label: Logo, name: logo, widget: image }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Hero, name: hero, widget: image }
      - file: "src/config/footer/index.md"
        label: "Footer"
        name: "footer"
        fields:
          - {
              label: "Config Type",
              name: "configType",
              widget: "hidden",
              default: "footer",
            }
          - { label: Name, name: name, widget: string }
          - { label: Address, name: address, widget: string }
          - { label: Data, name: data, widget: string }
          - { label: Logo, name: logo, widget: image }
  - name: "notifications"
    label: "Notification"
    folder: "src/pages/obavijesti"
    create: true
    slug: "{{slug}}-{{day}}-{{month}}-{{year}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "notification",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
  - name: "activities"
    label: "Activity"
    folder: "src/pages/aktivnosti"
    create: true
    slug: "{{slug}}-{{day}}-{{month}}-{{year}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "activity",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
      - file: "src/pages/kontakt/index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/clanstvo/index.md"
        label: "Members Page"
        name: "members"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "members-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/misija-i-vizija/index.md"
        label: "Vision Page"
        name: "vision"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "vision-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "Vision Image",
              name: image,
              widget: object,
              fields:
                [
                  { label: Image, name: src, widget: image },
                  {
                    label: "Image description",
                    name: alt,
                    widget: string,
                  },
                ],
            }
      - file: "src/pages/o-udruzi/index.md"
        label: "About Page"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: "Body", name: "body", widget: "markdown" }