backend:
  repo: test-repo
media_folder: static/assets
public_folder: /assets
collections:
  - name: notification
    label: Notification
    folder: notification
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }